# Generated by Django 2.2.1 on 2019-06-16 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('nome_do_medico', models.CharField(max_length=200)),
                ('idade', models.CharField(max_length=200)),
                ('formacao', models.CharField(max_length=200)),
                ('especializacao', models.CharField(max_length=200)),
                ('tempo_de_trabalho', models.CharField(max_length=200)),
                ('setor_de_trabalho', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
