# Generated by Django 2.2.1 on 2019-06-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='senha',
            field=models.CharField(default=12345678, max_length=10),
        ),
        migrations.AlterField(
            model_name='medico',
            name='status',
            field=models.CharField(choices=[('user', 'User'), ('superuser', 'Superuser')], default='user', max_length=2),
        ),
    ]
