# Generated by Django 2.2.1 on 2019-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=150)),
                ('idade', models.CharField(default='', max_length=3)),
                ('mae', models.CharField(default='', max_length=150)),
                ('pai', models.CharField(default='', max_length=150)),
                ('data_de_nascimento', models.CharField(default='', max_length=11)),
                ('doenca', models.CharField(default='', max_length=500)),
                ('alergia', models.CharField(default='', max_length=500)),
                ('tipo_de_atendimento', models.CharField(default='', max_length=15)),
                ('Data_de_atendimento', models.CharField(default='', max_length=11)),
                ('Setor_ambulatorial', models.CharField(default='', max_length=8)),
                ('Medico', models.CharField(default='', max_length=150)),
                ('Encaminhamentos', models.CharField(default='', max_length=500)),
                ('Evolucao', models.CharField(default='', max_length=500)),
                ('Exames', models.CharField(default='', max_length=500)),
                ('Prescricao', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
