# Generated by Django 2.2.1 on 2019-06-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpacientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pacientes',
        ),
    ]
