# Generated by Django 2.2.1 on 2019-05-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190526_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internacao',
            name='pacientes_ptr',
        ),
        migrations.DeleteModel(
            name='Ambulatorio',
        ),
        migrations.DeleteModel(
            name='Internacao',
        ),
    ]
