# Generated by Django 2.2.1 on 2019-06-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpacientes', '0003_ambulatorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ambulatorio',
        ),
    ]
