# Generated by Django 2.2.1 on 2019-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostaltas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='Data_de_atendimento',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='post',
            name='Encaminhamentos',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='Evolucao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='Exames',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='Medico',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='Prescricao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='Setor_ambulatorial',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='alergia',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='data_de_nascimento',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='post',
            name='doenca',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='idade',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='post',
            name='mae',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='nome',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='pai',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_de_atendimento',
            field=models.CharField(default='', max_length=15),
        ),
    ]
