# Generated by Django 2.2.1 on 2019-06-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mostaltas', '0002_auto_20190611_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
