# Generated by Django 2.2.1 on 2019-05-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=150)),
                ('idade', models.CharField(default='', max_length=3)),
                ('mae', models.CharField(default='', max_length=150)),
                ('pai', models.CharField(default='', max_length=150)),
                ('data_de_nascimento', models.CharField(default='', max_length=11)),
                ('doenca', models.CharField(default='', max_length=500)),
                ('alergia', models.CharField(default='', max_length=500)),
                ('tipo_de_atendimento', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ambulatorio',
            fields=[
                ('pacientes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Pacientes')),
            ],
            bases=('blog.pacientes',),
        ),
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('pacientes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Pacientes')),
            ],
            bases=('blog.pacientes',),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
