# Generated by Django 2.2.1 on 2019-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190526_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='Data_de_atendimento',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Encaminhamentos',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Evolucao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Exames',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Medico',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Prescricao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Setor_ambulatorial',
            field=models.CharField(default='', max_length=8),
        ),
    ]
