# Generated by Django 2.2.1 on 2019-06-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostambulatorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulatorio',
            name='tipo_de_atendimento',
            field=models.CharField(choices=[('em alta', 'Em_alta'), ('internacao', 'Internacao'), ('ambulatorio', 'Ambulatorio')], max_length=2),
        ),
    ]
